In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("healthcare_raw_data.csv")
df.head()

,Patient_ID,Age,Gender,Race,Height_cm,Weight_kg,BMI,Blood_Pressure,Cholesterol,Glucose,...,Medication_Count,Hospital_Visits_Last_Year,Insurance_Type,Income_Level,City,Admission_Date,Discharge_Date,Length_of_Stay,Total_Hospital_Cost,Readmitted_30_Days
0,P0001,72,Male,Black,174,92,30.4,148/92,241,132,...,6,4,Medicare,Low,Baltimore,2026-01-04,2026-01-11,7,"$14,220.50",Yes
1,P0002,29,female,White,165,61,22.4,118/76,176,91,...,0,0,Private,Medium,Boston,01/08/2026,01/10/2026,2,"$3,180.00",No
2,P0003,64,MALE,Hispanic,68,98,32.9,145/88,263,142,...,5,3,Medicaid,Low,New Yrok,2026-01-11,2026-01-18,7,"$13,750.75",Yes
3,P0004,45,Female,Asian,160,77,30.1,132/84,198,126,...,2,1,Private,Medium,Chicago,01/12/2026,01/16/2026,4,"$7,930.20",No
4,P0005,83,male,Black,171,88,30.1,156/95,255,151,...,8,5,Medicare,Low,Detroit,2026-01-15,2026-01-25,10,"$21,400.90",Yes

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 50 non-null     object
 1   Age                        50 non-null     int64
 2   Gender                     50 non-null     object
 3   Race                       50 non-null     object
 4   Height_cm                  50 non-null     int64
 5   Weight_kg                  50 non-null     int64
 6   BMI                        50 non-null     float64
 7   Blood_Pressure             50 non-null     object
 8   Cholesterol                50 non-null     int64
 9   Glucose                    50 non-null     int64
 10  Heart_Rate                 50 non-null     int64
 11  Smoking_Status             50 non-null     object
 12  Alcohol_Use                30 non-null     object
 13  Exercise_Frequency         50 non-null     object
 14  Diabetes                   50 non-null     object
 15  Hypertension               50 non-null     object
 16  Heart_Disease              50 non-null     object
 17  Medication_Count           50 non-null     int64
 18  Hospital_Visits_Last_Year  50 non-null     int64
 19  Insurance_Type             50 non-null     object
 20  Income_Level               50 non-null     object
 21  City                       50 non-null     object
 22  Admission_Date             50 non-null     object
 23  Discharge_Date             50 non-null     object
 24  Length_of_Stay             50 non-null     int64
 25  Total_Hospital_Cost        50 non-null     object
 26  Readmitted_30_Days         50 non-null     object
dtypes: float64(1), int64(9), object(17)
memory usage: 10.7+ KB

In [3]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Cholesterol,Glucose,Heart_Rate,Medication_Count,Hospital_Visits_Last_Year,Length_of_Stay
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,58.600000,147.600000,83.200000,29.180000,226.600000,128.400000,85.00000,4.200000,2.600000,6.000000
std,19.510332,40.499937,13.176974,3.585344,34.158096,20.766928,8.08122,2.885573,1.873554,2.784798
min,29.000000,68.000000,61.000000,22.400000,176.000000,91.000000,72.00000,0.000000,0.000000,2.000000
25%,45.000000,160.000000,77.000000,30.100000,198.000000,126.000000,80.00000,2.000000,1.000000,4.000000
50%,64.000000,165.000000,88.000000,30.100000,241.000000,132.000000,88.00000,5.000000,3.000000,7.000000
75%,72.000000,171.000000,92.000000,30.400000,255.000000,142.000000,91.00000,6.000000,4.000000,7.000000
max,83.000000,174.000000,98.000000,32.900000,263.000000,151.000000,94.00000,8.000000,5.000000,10.000000

In [5]:
df.shape

(50, 27)

In [6]:
df.isnull().sum()

Patient_ID                    0
Age                           0
Gender                        0
Race                          0
Height_cm                     0
Weight_kg                     0
BMI                           0
Blood_Pressure                0
Cholesterol                   0
Glucose                       0
Heart_Rate                    0
Smoking_Status                0
Alcohol_Use                  20
Exercise_Frequency            0
Diabetes                      0
Hypertension                  0
Heart_Disease                 0
Medication_Count              0
Hospital_Visits_Last_Year     0
Insurance_Type                0
Income_Level                  0
City                          0
Admission_Date                0
Discharge_Date                0
Length_of_Stay                0
Total_Hospital_Cost           0
Readmitted_30_Days            0
dtype: int64

In [7]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Cholesterol,Glucose,Heart_Rate,Medication_Count,Hospital_Visits_Last_Year,Length_of_Stay
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,58.600000,147.600000,83.200000,29.180000,226.600000,128.400000,85.00000,4.200000,2.600000,6.000000
std,19.510332,40.499937,13.176974,3.585344,34.158096,20.766928,8.08122,2.885573,1.873554,2.784798
min,29.000000,68.000000,61.000000,22.400000,176.000000,91.000000,72.00000,0.000000,0.000000,2.000000
25%,45.000000,160.000000,77.000000,30.100000,198.000000,126.000000,80.00000,2.000000,1.000000,4.000000
50%,64.000000,165.000000,88.000000,30.100000,241.000000,132.000000,88.00000,5.000000,3.000000,7.000000
75%,72.000000,171.000000,92.000000,30.400000,255.000000,142.000000,91.00000,6.000000,4.000000,7.000000
max,83.000000,174.000000,98.000000,32.900000,263.000000,151.000000,94.00000,8.000000,5.000000,10.000000

In [8]:
df.duplicated().sum()

np.int64(0)